- name: Create a directory
  hosts: all
  tasks:
    - name: Ensure /var/www/html exists
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data